name: CI

on:
  pull_request:
    branches:
      - "**"

jobs:
  linux-x86:
    name: Linux x86_64
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        qt: ["5.15.2", "6.4.2"]
    steps:
      - uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt }}

      - run: sudo apt install -y libxkbcommon-x11-dev

      - name: Run qmake
        run: qmake

      - name: Build
        run: make
